swiftmailer:
    transport:        gmail
    username:         richarthur123@gmail.com
    password:         pirrouette93
    host:             ~
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
        allow_self_signed: true
        verify_peer: false
        verify_peer_name: false